apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - openshift-virtualization-app.yaml
  - kube-descheduler-app.yaml
  - node-health-app.yaml
  - compliance/compliance-app.yaml

