# kustomization.yaml (Root of Repo)
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  # Point to the overlays/cluster-config, NOT the whole cluster folder
  # This avoids the 'apps/' folder which contains the Application YAML
  - clusters/REPLACE_ME_CLUSTER/overlays/cluster-config
