apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-config
  namespace: openshift-gitops
spec:
  project: default
  sources:
    - repoURL: https://github.com/mmwillingham/openshift-automation
      targetRevision: HEAD
      path: clusters/cluster-fl5kt/overlays/cluster-config
    - repoURL: https://github.com/mmwillingham/openshift-automation
      targetRevision: HEAD
      path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m