apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-config
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/mmwillingham/openshift-automation
    targetRevision: HEAD
    path: clusters/cluster-fl5kt/overlays/cluster-config
  destination:
    server: https://kubernetes.default.svc
    namespace: cluster-config
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m