apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../apps/cluster-config/cluster-config-app.yaml
  - ../../apps/acm/acm-operator-app.yaml
  - ../../apps/acm/acm-instance-app.yaml
  - ../../apps/openshift-virtualization/openshift-virtualization-instance-app.yaml
  - ../../apps/openshift-virtualization/openshift-virtualization-operator-app.yaml
  - ../../apps/node-health/node-health-operator-app.yaml
  - ../../apps/node-health/node-health-instance-app.yaml
  - ../../apps/compliance/compliance-operator-app.yaml
  - ../../apps/kube-descheduler/kube-descheduler-operator-app.yaml
  - ../../apps/kube-descheduler/kube-descheduler-instance-app.yaml
