---
apiVersion: v1
kind: Namespace
metadata:
  name: vault-auth
---    
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-reviewer
  namespace: vault-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-reviewer-token
  namespace: vault-auth
  annotations:
    kubernetes.io/service-account.name: vault-reviewer
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-reviewer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: vault-reviewer
  namespace: vault-auth
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: vault-secrets-operator
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: vault-secrets-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
