apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/openshift-virtualization


patches:
  - path: patch-virt-operator.yaml
  - path: patch-virt-instance.yaml
