---
apiVersion: v1
kind: Namespace
metadata:
  name: vso-demo-space
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-app-secret
  namespace: vso-demo-space
spec:
  # Link to the VaultAuth you created in your previous step
  vaultAuthRef: vault-auth/static-auth
  mount: prod
  type: kv-v2
  path: cluster-2vccz/vso-demo-space/test-secret
  destination:
    name: k8s-app-secret  # This is the name of the Secret that will appear in OCP
    create: true
  refreshAfter: 60s
